# Generated by Django 4.2.5 on 2023-11-05 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='polls_product',
        ),
    ]
